export const labels = {
  appName: 'Mini ERP',
  appTagline: 'Inventory & Sales Management',
  nav: {
    dashboard: 'Dashboard',
    products: 'Products',
    sales: 'Sales',
    newSale: 'New Sale',
    logout: 'Logout',
  },
  auth: {
    login: 'Login',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    loginFailed: 'Login failed',
    testAccounts: 'Test accounts:',
  },
  dashboard: {
    title: 'Dashboard',
    subtitle: 'Overview of inventory and sales',
    totalProducts: 'Total Products',
    totalSales: 'Total Sales',
    totalRevenue: 'Total Revenue',
    lowStock: 'Low Stock Products (< 5)',
    noLowStock: 'No low stock products',
    loading: 'Loading dashboard...',
    loadError: 'Failed to load dashboard',
  },
  products: {
    title: 'Products',
    subtitle: 'Manage your product catalog',
    add: 'Add Product',
    edit: 'Edit Product',
    search: 'Search products...',
    filterCategory: 'Filter by category',
    loading: 'Loading products...',
    loadError: 'Failed to load products',
    deleteConfirm: 'Delete this product?',
    name: 'Name',
    sku: 'SKU',
    category: 'Category',
    purchasePrice: 'Purchase Price (৳)',
    sellingPrice: 'Selling Price (৳)',
    stock: 'Stock Quantity',
    image: 'Image',
    imageRequired: '(required)',
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    editBtn: 'Edit',
    deleteBtn: 'Delete',
    price: 'Price',
    actions: 'Actions',
    page: 'Page',
    of: 'of',
    total: 'total',
    previous: 'Previous',
    next: 'Next',
  },
  sales: {
    title: 'Sales History',
    subtitle: 'View past sales transactions',
    newSale: 'New Sale',
    createTitle: 'Create Sale',
    createSubtitle: 'Add products and record a new sale',
    addProducts: 'Add Products',
    lineItems: 'Line Items',
    searchProduct: 'Search products to add...',
    add: 'Add',
    remove: 'Remove',
    product: 'Product',
    unitPrice: 'Unit Price',
    qty: 'Qty',
    subtotal: 'Subtotal',
    grandTotal: 'Grand Total',
    previewNote: 'Preview only — server computes the final total',
    complete: 'Complete Sale',
    creating: 'Creating...',
    addItemError: 'Add at least one item',
    createError: 'Failed to create sale',
    loading: 'Loading sales...',
    loadError: 'Failed to load sales',
    date: 'Date',
    items: 'items',
    soldBy: 'Sold By',
    noItems: 'No items added yet',
    stock: 'Stock',
  },
  table: {
    name: 'Name',
    sku: 'SKU',
    category: 'Category',
    stock: 'Stock',
    image: 'Image',
  },
} as const;
